<?php
// Central multilingual content for the 13 legal service areas, shared by
// index.php (teaser grid) and sluzby.php (full detail sections).
// Each entry keeps the original Czech field plus _en / _de counterparts,
// read through tf()/tfArr() from includes/i18n.php.

return [
  [
    'id' => 'obchodni-pravo-a-korporatni-agenda',
    'label' => 'Obchodní právo a korporátní agenda',
    'label_en' => 'Commercial law and corporate affairs',
    'label_de' => 'Handelsrecht und Unternehmensangelegenheiten',
    'desc' => 'Zakládání, správa a rozvoj podnikání bez právních rizik a zbytečné administrativy.',
    'desc_en' => 'Setting up, managing and developing a business without legal risks or unnecessary red tape.',
    'desc_de' => 'Gründung, Verwaltung und Entwicklung eines Unternehmens ohne rechtliche Risiken und unnötigen Verwaltungsaufwand.',
    'bullets' => [
      'Zakládání a změny společností, valné hromady a převody podílů',
      'Obchodní smlouvy na míru a smluvní vyjednávání',
      'Fúze, akvizice (M&A) a právní prověrky (Due Diligence)',
    ],
    'bullets_en' => [
      'Company formation and amendments, general meetings and share transfers',
      'Tailor-made commercial contracts and contract negotiations',
      'Mergers, acquisitions (M&A) and due diligence',
    ],
    'bullets_de' => [
      'Gründung und Änderung von Gesellschaften, Hauptversammlungen und Anteilsübertragungen',
      'Maßgeschneiderte Handelsverträge und Vertragsverhandlungen',
      'Fusionen, Übernahmen (M&A) und rechtliche Prüfungen (Due Diligence)',
    ],
  ],
  [
    'id' => 'pracovni-pravo',
    'label' => 'Pracovní právo',
    'label_en' => 'Employment law',
    'label_de' => 'Arbeitsrecht',
    'desc' => 'Ochrana práv a zájmů zaměstnavatelů i zaměstnanců při každodenních i krizových situacích.',
    'desc_en' => 'Protecting the rights and interests of both employers and employees in day-to-day and crisis situations.',
    'desc_de' => 'Schutz der Rechte und Interessen von Arbeitgebern und Arbeitnehmern in alltäglichen und krisenhaften Situationen.',
    'bullets' => [
      'Pracovní smlouvy, manažerské kontrakty a dohody',
      'Ukončení pracovního poměru a spory o neplatnost výpovědi',
      'Vnitřní předpisy, compliance a odměňování',
    ],
    'bullets_en' => [
      'Employment contracts, executive contracts and agreements',
      'Termination of employment and disputes regarding the invalidity of notice',
      'Internal regulations, compliance and remuneration',
    ],
    'bullets_de' => [
      'Arbeitsverträge, Geschäftsführerverträge und Vereinbarungen',
      'Beendigung des Arbeitsverhältnisses und Streitigkeiten über die Unwirksamkeit der Kündigung',
      'Interne Vorschriften, Compliance und Vergütung',
    ],
  ],
  [
    'id' => 'pravo-nemovitosti-a-stavebni-pravo',
    'label' => 'Nemovitosti a stavební právo',
    'label_en' => 'Property and construction law',
    'label_de' => 'Immobilien- und Baurecht',
    'desc' => 'Bezpečné investice, prodeje i vývoj nemovitostí s kompletním právním servisem.',
    'desc_en' => 'Secure property investments, sales and development with a comprehensive legal service.',
    'desc_de' => 'Sichere Immobilieninvestitionen, Verkäufe und Projektentwicklung mit umfassendem Rechtsservice.',
    'bullets' => [
      'Koupě, prodej a pronájem nemovitostí včetně advokátní úschovy',
      'Právní prověrky nemovitostí (Due Diligence) a věcná břemena',
      'Stavební řízení, developerské projekty a územní plánování',
    ],
    'bullets_en' => [
      'Purchase, sale and letting of property, including escrow services',
      'Legal due diligence on property and easements',
      'Planning permission procedures, property development projects and spatial planning',
    ],
    'bullets_de' => [
      'Kauf, Verkauf und Vermietung von Immobilien, einschließlich Treuhanddiensten',
      'Rechtliche Prüfung von Immobilien (Due Diligence) und Dienstbarkeiten',
      'Bau- und Planungsverfahren, Immobilienentwicklungsprojekte und Raumplanung',
    ],
  ],
  [
    'id' => 'sporna-agenda-a-rozhodci-rizeni',
    'label' => 'Sporná agenda a rozhodčí řízení',
    'label_en' => 'Litigation and arbitration',
    'label_de' => 'Streitbeilegung und Schiedsverfahren',
    'desc' => 'Zastoupení před soudy, rozhodci i úřady s cílením na efektivní a rychlé řešení.',
    'desc_en' => 'Representation before courts, arbitrators and regulatory authorities, with a focus on effective and swift resolution.',
    'desc_de' => 'Vertretung vor Gerichten, Schiedsrichtern und Behörden mit dem Ziel einer wirksamen und schnellen Lösung.',
    'bullets' => [
      'Komplexní zastupování v občanskoprávních i obchodních sporech',
      'Mimosoudní jednání, mediace a smírčí řešení',
      'Správní soudnictví a ústavní stížnosti',
    ],
    'bullets_en' => [
      'Comprehensive representation in civil and commercial disputes',
      'Out-of-court negotiations, mediation and settlement',
      'Administrative justice and constitutional complaints',
    ],
    'bullets_de' => [
      'Umfassende Vertretung in zivil- und handelsrechtlichen Streitigkeiten',
      'Außergerichtliche Verhandlungen, Mediation und gütliche Einigung',
      'Verwaltungsgerichtsbarkeit und Verfassungsbeschwerden',
    ],
  ],
  [
    'id' => 'trestni-pravo',
    'label' => 'Trestní právo a obhajoba',
    'label_en' => 'Criminal law and defence',
    'label_de' => 'Strafrecht und Strafverteidigung',
    'desc' => 'Důsledná obhajoba osob a zastupování právnických osob v trestním řízení.',
    'desc_en' => 'Thorough defence of individuals and representation of legal entities in criminal proceedings.',
    'desc_de' => 'Konsequente Verteidigung von Einzelpersonen und Vertretung juristischer Personen im Strafverfahren.',
    'bullets' => [
      'Obhajoba v celém průběhu trestního řízení (od podání vysvětlení po soud)',
      'Zastupování poškozených a uplatňování nároku na náhradu škody',
      'Trestní odpovědnost právnických osob a řešení hospodářské kriminality',
    ],
    'bullets_en' => [
      'Defence throughout the entire course of criminal proceedings (from giving a statement to the trial)',
      'Representation of victims and assertion of claims for damages',
      'Criminal liability of legal entities and handling of white-collar crime',
    ],
    'bullets_de' => [
      'Verteidigung während des gesamten Strafverfahrens (von der Aussage bis zur Hauptverhandlung)',
      'Vertretung von Geschädigten und Durchsetzung von Schadensersatzansprüchen',
      'Strafrechtliche Verantwortlichkeit juristischer Personen und Wirtschaftskriminalität',
    ],
  ],
  [
    'id' => 'rodinne-pravo',
    'label' => 'Rodinné právo a majetkové vztahy',
    'label_en' => 'Family law and property relations',
    'label_de' => 'Familienrecht und Vermögensverhältnisse',
    'desc' => 'Citlivé a profesionální řešení rodinných záležitostí s důrazem na zájem dětí.',
    'desc_en' => 'Sensitive and professional handling of family matters, with an emphasis on the best interests of the children.',
    'desc_de' => 'Sensible und professionelle Behandlung von Familienangelegenheiten mit Schwerpunkt auf dem Kindeswohl.',
    'bullets' => [
      'Rozvody manželství (sporné i nesporné) a vypořádání SJM',
      'Péče o nezletilé děti, výživné a úprava styku',
      'Předmanželské smlouvy a úprava majetkových poměrů',
    ],
    'bullets_en' => [
      'Divorce (contested and uncontested) and the division of joint marital property',
      'Custody of minor children, maintenance and access arrangements',
      'Prenuptial agreements and the regulation of property relations',
    ],
    'bullets_de' => [
      'Ehescheidung (streitig und einvernehmlich) und Aufteilung des ehelichen Gemeinschaftsvermögens',
      'Sorgerecht für minderjährige Kinder, Unterhalt und Umgangsregelung',
      'Eheverträge und Regelung der Vermögensverhältnisse',
    ],
  ],
  [
    'id' => 'obcanske-pravo-a-smluvni-agenda',
    'label' => 'Občanské právo a smluvní agenda',
    'label_en' => 'Civil law and contractual matters',
    'label_de' => 'Zivilrecht und Vertragsangelegenheiten',
    'desc' => 'Příprava a revize smluv pro jistotu ve vašich každodenních právních vztazích.',
    'desc_en' => 'Drafting and reviewing contracts to ensure certainty in your day-to-day legal relationships.',
    'desc_de' => 'Erstellung und Prüfung von Verträgen für Rechtssicherheit in Ihren alltäglichen Rechtsbeziehungen.',
    'bullets' => [
      'Kupní, darovací, nájemní a zprostředkovatelské smlouvy',
      'Náhrada škody, nemajetkové újmy a bezdůvodné obohacení',
      'Ochrana osobnosti a řešení sousedských sporů',
    ],
    'bullets_en' => [
      'Sale, gift, tenancy and agency agreements',
      'Compensation for damages, non-pecuniary harm and unjust enrichment',
      'Protection of personality rights and resolution of neighbourhood disputes',
    ],
    'bullets_de' => [
      'Kauf-, Schenkungs-, Miet- und Vermittlungsverträge',
      'Schadensersatz, immaterieller Schaden und ungerechtfertigte Bereicherung',
      'Persönlichkeitsschutz und Beilegung von Nachbarschaftsstreitigkeiten',
    ],
  ],
  [
    'id' => 'ma-a-reorganizace',
    'label' => 'M&A a reorganizace',
    'label_en' => 'M&A and reorganisation',
    'label_de' => 'M&A und Reorganisation',
    'desc' => 'Právní podpora při prodeji, nákupu nebo strukturálních změnách firem.',
    'desc_en' => 'Legal support for the sale, purchase or structural changes to companies.',
    'desc_de' => 'Rechtliche Unterstützung beim Verkauf, Kauf oder bei strukturellen Veränderungen von Unternehmen.',
    'bullets' => [
      'Příprava transakční dokumentace a strukturování obchodu',
      'Řízení procesu Due Diligence a posouzení rizik',
      'Post-transakční integrace a reorganizace podniku',
    ],
    'bullets_en' => [
      'Preparation of transaction documentation and structuring of the deal',
      'Management of the due diligence process and risk assessment',
      'Post-transaction integration and corporate reorganisation',
    ],
    'bullets_de' => [
      'Erstellung der Transaktionsdokumentation und Strukturierung des Geschäfts',
      'Steuerung des Due-Diligence-Prozesses und Risikobewertung',
      'Post-Merger-Integration und Unternehmensreorganisation',
    ],
  ],
  [
    'id' => 'vymahani-a-sprava-pohledavek',
    'label' => 'Vymáhání pohledávek a exekuce',
    'label_en' => 'Debt recovery and enforcement',
    'label_de' => 'Forderungseinzug und Zwangsvollstreckung',
    'desc' => 'Rychlá a efektivní správa i vymáhání vašich finančních nároků.',
    'desc_en' => 'Swift and effective management and recovery of your financial claims.',
    'desc_de' => 'Schnelle und wirksame Verwaltung und Beitreibung Ihrer finanziellen Forderungen.',
    'bullets' => [
      'Předžalobní výzvy, platební rozkazy a žaloby na plnění',
      'Zastupování v exekučním a vykonávacím řízení',
      'Přihlašování pohledávek a správa pohledávkových portfolií',
    ],
    'bullets_en' => [
      'Pre-action notices, payment orders and actions for specific performance',
      'Representation in enforcement and execution proceedings',
      'Filing of claims and management of debt portfolios',
    ],
    'bullets_de' => [
      'Mahnschreiben, Zahlungsbefehle und Klagen auf Erfüllung',
      'Vertretung im Vollstreckungs- und Exekutionsverfahren',
      'Anmeldung von Forderungen und Verwaltung von Forderungsportfolios',
    ],
  ],
  [
    'id' => 'insolvencni-pravo',
    'label' => 'Insolvenční právo a restrukturalizace',
    'label_en' => 'Insolvency law and restructuring',
    'label_de' => 'Insolvenzrecht und Restrukturierung',
    'desc' => 'Řešení úpadku, oddlužení a ochrana práv věřitelů i dlužníků.',
    'desc_en' => 'Handling insolvency, debt relief and the protection of the rights of both creditors and debtors.',
    'desc_de' => 'Abwicklung von Insolvenzen, Entschuldung und Schutz der Rechte von Gläubigern und Schuldnern.',
    'bullets' => [
      'Insolvenční návrhy (předlužení, úpadek) a přihlášky pohledávek',
      'Zastupování v incidenčních sporech a insolvenčních řízeních',
      'Reorganizace podniků a preventivní restrukturalizace',
    ],
    'bullets_en' => [
      'Insolvency petitions (over-indebtedness, bankruptcy) and filing of claims',
      'Representation in incidental disputes and insolvency proceedings',
      'Corporate reorganisation and preventative restructuring',
    ],
    'bullets_de' => [
      'Insolvenzanträge (Überschuldung, Zahlungsunfähigkeit) und Forderungsanmeldungen',
      'Vertretung in Nebenstreitigkeiten und Insolvenzverfahren',
      'Unternehmensreorganisation und präventive Restrukturierung',
    ],
  ],
  [
    'id' => 'dusevni-vlastnictvi-a-it-pravo',
    'label' => 'Duševní vlastnictví a IT právo',
    'label_en' => 'Intellectual property and IT law',
    'label_de' => 'Geistiges Eigentum und IT-Recht',
    'desc' => 'Právní ochrana vašich nápadů, softwaru, značek a digitálního podnikání.',
    'desc_en' => 'Legal protection for your ideas, software, trademarks and digital business.',
    'desc_de' => 'Rechtlicher Schutz für Ihre Ideen, Software, Marken und Ihr digitales Geschäft.',
    'bullets' => [
      'Ochranné známky, patenty a autorská práva',
      'Softwarové smlouvy (SLA, SaaS, vývoj softwaru)',
      'Právní úprava e-commerce, webů a obchodních podmínek',
    ],
    'bullets_en' => [
      'Trade marks, patents and copyright',
      'Software contracts (SLA, SaaS, software development)',
      'Legal framework for e-commerce, websites and terms and conditions',
    ],
    'bullets_de' => [
      'Marken, Patente und Urheberrecht',
      'Softwareverträge (SLA, SaaS, Softwareentwicklung)',
      'Rechtlicher Rahmen für E-Commerce, Websites und AGB',
    ],
  ],
  [
    'id' => 'ochrana-osobnich-udaju-gdpr-a-compliance',
    'label' => 'Ochrana osobních údajů (GDPR) a compliance',
    'label_en' => 'Data protection (GDPR) and compliance',
    'label_de' => 'Datenschutz (DSGVO) und Compliance',
    'desc' => 'Nastavení interních procesů pro soulad s legislativou a minimalizaci pokut.',
    'desc_en' => 'Setting up internal processes to ensure compliance with legislation and minimise fines.',
    'desc_de' => 'Einrichtung interner Prozesse zur Einhaltung der Gesetzgebung und Minimierung von Bußgeldern.',
    'bullets' => [
      'Kompletní auditorská příprava na GDPR a implementace',
      'Příprava předpisů, souhlasů a dokumentace ochrany dat',
      'Nastavení interních whistleblower systémů (ochrana oznamovatelů)',
    ],
    'bullets_en' => [
      'Comprehensive audit preparation for GDPR and implementation',
      'Drafting of data protection policies, consents and documentation',
      'Setting up internal whistleblower systems (protection of whistleblowers)',
    ],
    'bullets_de' => [
      'Umfassende Auditvorbereitung für die DSGVO und Umsetzung',
      'Erstellung von Datenschutzrichtlinien, Einwilligungen und Dokumentation',
      'Einrichtung interner Whistleblower-Systeme (Hinweisgeberschutz)',
    ],
  ],
  [
    'id' => 'zastupovani-pred-urady-a-spravni-pravo',
    'label' => 'Zastupování před úřady a správní právo',
    'label_en' => 'Representation before authorities and administrative law',
    'label_de' => 'Vertretung vor Behörden und Verwaltungsrecht',
    'desc' => 'Právní pomoc při jednání s orgány státní správy a samosprávy.',
    'desc_en' => 'Legal assistance in dealings with central and local government bodies.',
    'desc_de' => 'Rechtliche Unterstützung im Umgang mit staatlichen und kommunalen Behörden.',
    'bullets' => [
      'Správní řízení, přestupková agenda a stavební úřady',
      'Podávání odvolání, rozkladů a správních žalob',
      'Zastupování při kontrolách finančních a jiných úřadů',
    ],
    'bullets_en' => [
      'Administrative proceedings, minor offences and planning authorities',
      'Lodging appeals, objections and administrative actions',
      'Representation during inspections by financial and other authorities',
    ],
    'bullets_de' => [
      'Verwaltungsverfahren, Ordnungswidrigkeiten und Bauämter',
      'Einlegung von Rechtsmitteln, Widersprüchen und Verwaltungsklagen',
      'Vertretung bei Prüfungen durch Finanz- und andere Behörden',
    ],
  ],
];
